name: pick_app
description: A new share location project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.6.2
  webview_flutter: ^3.0.0
  flutter_inappwebview: ^5.3.2
  permission_handler: ^9.0.1
  cupertino_icons: ^1.0.2
  receive_sharing_intent: ^1.4.5
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#42a5f5"
  fullscreen: true
